export const VOICE_LANGUAGES = [
  { code: "en-IN", label: "English (India)" },
  { code: "te-IN", label: "తెలుగు (Telugu)" },
  { code: "hi-IN", label: "हिन्दी (Hindi)" },
  { code: "kn-IN", label: "ಕನ್ನಡ (Kannada)" },
  { code: "ta-IN", label: "தமிழ் (Tamil)" },
  { code: "ml-IN", label: "മലയാളം (Malayalam)" },
  { code: "mr-IN", label: "मराठी (Marathi)" },
  { code: "bn-IN", label: "বাংলা (Bengali)" },
];

const TELUGU_PRODUCT_ALIASES = [
  {
    catalogNames: ["tomato", "tomatoes"],
    aliases: ["టమాటా", "టమోటా", "టొమాటో", "టమాట", "tomato"],
    speechVariants: [],
  },
  {
    catalogNames: ["chilli", "chillies", "green chilli", "green chillies", "mirchi"],
    aliases: [
      "మిర్చి",
      "మిరపకాయ",
      "మిరప",
      "పచ్చిమిర్చి",
      "chilli",
      "green chilli",
      "mirchi",
    ],
    speechVariants: [],
  },
  {
    catalogNames: ["onion", "onions"],
    aliases: [
      "ఉల్లిపాయ",
      "ఉల్లిపాయలు",
      "ఆనియన్",
      "ఆనియన్స్",
      "onion",
      "onions",
    ],
    speechVariants: [
      { phrase: "ఆన యన", alias: "ఆనియన్" },
      { phrase: "ఆనియన్", alias: "ఆనియన్" },
      { phrase: "ఆన యన్స్", alias: "ఆనియన్స్" },
    ],
  },
  {
    catalogNames: ["brinjal", "brinjals", "eggplant", "eggplants"],
    aliases: ["వంకాయ", "వంకాయలు", "brinjal", "eggplant"],
    speechVariants: [],
  },
  {
    catalogNames: ["potato", "potatoes"],
    aliases: ["బంగాళాదుంప", "ఆలుగడ్డ", "potato", "potatoes"],
    speechVariants: [],
  },
];

const normalizeAliasName = (value) =>
  value.toLowerCase().normalize("NFKC").replace(/[^\p{L}\p{N}\s]/gu, " ").replace(/\s+/gu, " ").trim();

export const getTeluguProductAliases = (catalogProductName) => {
  const normalizedName = normalizeAliasName(catalogProductName || "");
  return (
    TELUGU_PRODUCT_ALIASES.find(({ catalogNames }) =>
      catalogNames.some((name) => normalizeAliasName(name) === normalizedName)
    )?.aliases || []
  );
};

export const normalizeTeluguProductSpacing = (transcript) => {
  let normalized = transcript;
  for (const { speechVariants } of TELUGU_PRODUCT_ALIASES) {
    for (const { phrase, alias } of speechVariants) {
      const escapedPhrase = phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replace(/\s+/gu, "\\s+");
      normalized = normalized.replace(
        new RegExp(`(^|[^\\p{L}\\p{N}])(${escapedPhrase})(?=$|[^\\p{L}\\p{N}])`, "giu"),
        (_match, prefix) => `${prefix}${alias}`
      );
    }
  }
  return normalized;
};

const INTENTS = {
  "en-IN": {
    cancel: /\b(cancel|no|don't|do not)\b/i,
    confirm: /\b(yes|proceed|add to cart|okay|ok|confirm)\b/i,
    checkout: /\b(check ?out|proceed|pay|yes|continue to checkout)\b/i,
    shopping: /\b(shop|continue shopping|not now|no)\b/i,
  },
  "te-IN": {
    cancel: /రద్దు|వద్దు|కాదు|వద్దు చేయండి/u,
    confirm: /అవును|సరే|నిర్ధారించు|జోడించండి/u,
    checkout: /చెక్అవుట్|చెల్లించు|కొనసాగించు|అవును/u,
    shopping: /షాపింగ్ కొనసాగించు|ఇప్పుడు వద్దు|లేదు/u,
  },
  "hi-IN": {
    cancel: /रद्द|नहीं|मत जोड़ो/u,
    confirm: /हाँ|हां|ठीक|पुष्टि|जोड़ो/u,
    checkout: /चेकआउट|भुगतान|आगे बढ़ें|हाँ|हां/u,
    shopping: /खरीदारी जारी|अभी नहीं|नहीं/u,
  },
  "kn-IN": {
    cancel: /ರದ್ದು|ಬೇಡ|ಇಲ್ಲ/u,
    confirm: /ಹೌದು|ಸರಿ|ದೃಢೀಕರಿಸಿ|ಸೇರಿಸಿ/u,
    checkout: /ಚೆಕ್‌?ಔಟ್|ಪಾವತಿ|ಮುಂದುವರಿಸಿ|ಹೌದು/u,
    shopping: /ಶಾಪಿಂಗ್ ಮುಂದುವರಿಸಿ|ಈಗ ಬೇಡ|ಇಲ್ಲ/u,
  },
  "ta-IN": {
    cancel: /ரத்து|வேண்டாம்|இல்லை/u,
    confirm: /ஆம்|சரி|உறுதிசெய்|சேர்க்கவும்/u,
    checkout: /செக்அவுட்|பணம் செலுத்த|தொடரவும்|ஆம்/u,
    shopping: /ஷாப்பிங்கைத் தொடர|இப்போது வேண்டாம்|இல்லை/u,
  },
  "ml-IN": {
    cancel: /റദ്ദ്|വേണ്ട|ഇല്ല/u,
    confirm: /അതെ|ശരി|ഉറപ്പാക്കൂ|ചേർക്കുക/u,
    checkout: /ചെക്ക്ഔട്ട്|പണമടയ്ക്ക|തുടരുക|അതെ/u,
    shopping: /ഷോപ്പിംഗ് തുടര|ഇപ്പോൾ വേണ്ട|ഇല്ല/u,
  },
  "mr-IN": {
    cancel: /रद्द|नाही|नको/u,
    confirm: /हो|ठीक|पुष्टी|जोडा/u,
    checkout: /चेकआउट|पैसे भरा|पुढे जा|हो/u,
    shopping: /खरेदी सुरू ठेवा|आत्ता नको|नाही/u,
  },
  "bn-IN": {
    cancel: /বাতিল|না|যোগ করবেন না/u,
    confirm: /হ্যাঁ|ঠিক আছে|নিশ্চিত|যোগ করুন/u,
    checkout: /চেকআউট|পেমেন্ট|এগিয়ে যান|হ্যাঁ/u,
    shopping: /কেনাকাটা চালিয়ে যান|এখন নয়|না/u,
  },
};

export const hasVoiceIntent = (text, languageCode, intent) =>
  (INTENTS[languageCode] || INTENTS["en-IN"])[intent]?.test(text) || false;

const COPY = {
  "en-IN": {
    greeting: (name) => `Hi${name ? ` ${name}` : ""}! What would you like to order?`,
    loadingError: "I couldn't load the product list. Please reconnect or refresh the page.",
    notRecognized: "I couldn't identify a product and quantity. Try “tomato one kg and brinjal half kg”.",
    unsupported: "Speech recognition isn't supported by this browser. Please try Chrome or add products manually.",
    micDenied: "Microphone permission was denied. Allow microphone access in your browser and try again.",
    speechFailed: "Speech recognition failed. Please try again or add products manually.",
    micFailed: "I couldn't start the microphone. Check browser permissions and try again.",
    notAvailable: (names) => `Sorry, ${names} ${names.includes(",") ? "are" : "is"} not available in our product list and won't be added.`,
    outOfStock: (names) => `Sorry, ${names} ${names.includes(",") ? "are" : "is"} currently out of stock.`,
    alreadyCart: (names) => `All currently available stock for ${names} is already in your cart, so I can't add more.`,
    stockUnknown: (names) => `I couldn't verify stock or pricing for ${names}. Those items won't be added.`,
    review: (items, total) => `Your order total is ₹${total}. I found ${items}. Would you like me to add these items to your cart?`,
    minimumOrder: (total, minimum) => `Your current order total is ₹${total}. The minimum order value is ₹${minimum}. Please add another item or increase the quantity.`,
    reviewAgain: "Please confirm the order summary or cancel it before starting another request.",
    approvalNeeded: "Please choose whether to accept the available quantity before I add these items.",
    cancelled: "Okay, I cancelled that voice order.",
    itemRemoved: "That item was removed from this voice order.",
    itemRemovedLast: "That item was removed from this voice order.",
    cartAdded: "Your items have been added to the cart. Would you like to proceed to checkout?",
    cartError: "I couldn't update your cart. Please try again or add the items manually.",
    continueBrowsing: "No problem. You can continue browsing products.",
    proceedPrompt: "Say 'proceed to checkout' or choose 'Continue Shopping'.",
    unavailableError: "I couldn't load the product list. Please try again after reconnecting or refresh the page.",
    didntCatch: "I didn't catch that. Please try speaking again.",
    noSpeech: "Please confirm the order summary or cancel it before starting another request.",
    listening: "Listening…",
    userSaid: "You said",
    order: "Your Order",
    onlyAvailable: (quantity, name) => `Only ${quantity} kg of ${name} is available. Add the available quantity?`,
    addAvailable: (quantity) => `Add ${quantity} kg`,
    cancelItem: "Cancel item",
    availableAccepted: "Available quantity accepted.",
    estimatedTotal: "Estimated total",
    confirmAdd: "Confirm & Add to Cart",
    adding: "Adding…",
    checkout: "Proceed to Checkout",
    continueShopping: "Continue Shopping",
    startVoice: "Start voice order",
    starting: "Starting…",
  },
  "te-IN": {
    greeting: (name) => `నమస్కారం${name ? ` ${name}` : ""}! ఏమి ఆర్డర్ చేయాలనుకుంటున్నారు?`,
    loadingError: "ఉత్పత్తుల జాబితాను లోడ్ చేయలేకపోయాను. మళ్లీ కనెక్ట్ చేసి పేజీని రిఫ్రెష్ చేయండి.",
    notRecognized: "ఉత్పత్తి మరియు పరిమాణాన్ని గుర్తించలేకపోయాను. ఉదాహరణకు టమాటా ఒక కిలో అని చెప్పండి.",
    unsupported: "ఈ బ్రౌజర్‌లో వాయిస్ గుర్తింపు అందుబాటులో లేదు. Chrome ప్రయత్నించండి లేదా ఉత్పత్తులను మాన్యువల్‌గా జోడించండి.",
    micDenied: "మైక్రోఫోన్ అనుమతి నిరాకరించబడింది. బ్రౌజర్‌లో అనుమతించి మళ్లీ ప్రయత్నించండి.",
    speechFailed: "వాయిస్ గుర్తింపు విఫలమైంది. మళ్లీ ప్రయత్నించండి లేదా ఉత్పత్తులను మాన్యువల్‌గా జోడించండి.",
    micFailed: "మైక్రోఫోన్ ప్రారంభం కాలేదు. అనుమతులను తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.",
    notAvailable: (names) => `${names} మా ఉత్పత్తుల జాబితాలో లేవు; జోడించబడవు.`,
    outOfStock: (names) => `${names} ప్రస్తుతం స్టాక్‌లో లేవు.`,
    alreadyCart: (names) => `${names} అందుబాటులో ఉన్న స్టాక్ ఇప్పటికే మీ కార్ట్‌లో ఉంది.`,
    stockUnknown: (names) => `${names} స్టాక్ లేదా ధరను తనిఖీ చేయలేకపోయాను. అవి జోడించబడవు.`,
    review: (items, total) => `మీ ఆర్డర్ మొత్తం ₹${total}. ${items} కనుగొన్నాను. ఈ ఉత్పత్తులను కార్ట్‌లో జోడించాలా?`,
    minimumOrder: (total, minimum) => `మీ ప్రస్తుత ఆర్డర్ మొత్తం ₹${total}. కనీస ఆర్డర్ విలువ ₹${minimum}. దయచేసి మరొక ఉత్పత్తిని జోడించండి లేదా పరిమాణాన్ని పెంచండి.`,
    reviewAgain: "మరొక అభ్యర్థనకు ముందు ఆర్డర్‌ను నిర్ధారించండి లేదా రద్దు చేయండి.",
    approvalNeeded: "జోడించే ముందు అందుబాటులో ఉన్న పరిమాణాన్ని అంగీకరించాలా ఎంచుకోండి.",
    cancelled: "సరే, వాయిస్ ఆర్డర్‌ను రద్దు చేశాను.",
    itemRemoved: "ఈ వాయిస్ ఆర్డర్ నుంచి ఉత్పత్తిని తొలగించాను.",
    itemRemovedLast: "ఈ వాయిస్ ఆర్డర్ నుంచి ఉత్పత్తిని తొలగించాను.",
    cartAdded: "మీ ఉత్పత్తులు కార్ట్‌లో జోడించబడ్డాయి. చెక్అవుట్‌కు వెళ్లాలా?",
    cartError: "కార్ట్‌ను నవీకరించలేకపోయాను. మళ్లీ ప్రయత్నించండి లేదా మాన్యువల్‌గా జోడించండి.",
    continueBrowsing: "సరే. ఉత్పత్తులను చూడటం కొనసాగించండి.",
    proceedPrompt: "చెక్అవుట్‌కు వెళ్లండి అని చెప్పండి లేదా షాపింగ్ కొనసాగించండి ఎంచుకోండి.",
    unavailableError: "ఉత్పత్తుల జాబితాను లోడ్ చేయలేకపోయాను. మళ్లీ కనెక్ట్ చేసి పేజీని రిఫ్రెష్ చేయండి.",
    didntCatch: "మీ మాట వినబడలేదు. మళ్లీ మాట్లాడండి.",
    noSpeech: "మీ మాట వినబడలేదు. మళ్లీ మాట్లాడండి.",
    listening: "వింటున్నాను…",
    userSaid: "మీరు చెప్పింది",
    order: "మీ ఆర్డర్",
    onlyAvailable: (quantity, name) => `${name} ${quantity} కిలోలు మాత్రమే ఉన్నాయి. అందుబాటులో ఉన్నవి జోడించాలా?`,
    addAvailable: (quantity) => `${quantity} కిలోలు జోడించండి`,
    cancelItem: "ఉత్పత్తిని రద్దు చేయండి",
    availableAccepted: "అందుబాటులో ఉన్న పరిమాణం అంగీకరించబడింది.",
    estimatedTotal: "అంచనా మొత్తం",
    confirmAdd: "నిర్ధారించి కార్ట్‌లో జోడించండి",
    adding: "జోడిస్తోంది…",
    checkout: "చెక్అవుట్‌కు వెళ్లండి",
    continueShopping: "షాపింగ్ కొనసాగించండి",
    startVoice: "వాయిస్ ఆర్డర్ ప్రారంభించండి",
    starting: "ప్రారంభిస్తోంది…",
  },
  "hi-IN": {
    greeting: (name) => `नमस्ते${name ? ` ${name}` : ""}! आप क्या ऑर्डर करना चाहेंगे?`,
    loadingError: "उत्पाद सूची लोड नहीं हो सकी। फिर से कनेक्ट करें या पेज रीफ़्रेश करें।",
    notRecognized: "उत्पाद और मात्रा समझ नहीं आई। जैसे: टमाटर एक किलो और बैंगन आधा किलो।",
    unsupported: "इस ब्राउज़र में वॉइस पहचान उपलब्ध नहीं है। Chrome आज़माएँ या उत्पाद मैन्युअल रूप से जोड़ें।",
    micDenied: "माइक्रोफ़ोन अनुमति नहीं मिली। ब्राउज़र में अनुमति देकर फिर कोशिश करें।",
    speechFailed: "वॉइस पहचान विफल हुई। फिर कोशिश करें या उत्पाद मैन्युअल रूप से जोड़ें।",
    micFailed: "माइक्रोफ़ोन शुरू नहीं हो सका। अनुमति जाँचकर फिर कोशिश करें।",
    notAvailable: (names) => `${names} हमारी उत्पाद सूची में उपलब्ध नहीं हैं और नहीं जोड़े जाएंगे।`,
    outOfStock: (names) => `${names} अभी स्टॉक में नहीं हैं।`,
    alreadyCart: (names) => `${names} का उपलब्ध स्टॉक पहले से आपके कार्ट में है।`,
    stockUnknown: (names) => `${names} का स्टॉक या कीमत जाँच नहीं सका। इन्हें नहीं जोड़ा जाएगा।`,
    review: (items, total) => `आपके ऑर्डर का कुल ₹${total} है। ${items} मिले। क्या इन्हें कार्ट में जोड़ें?`,
    minimumOrder: (total, minimum) => `आपके ऑर्डर का कुल ₹${total} है। न्यूनतम ऑर्डर मूल्य ₹${minimum} है। कृपया एक और उत्पाद जोड़ें या मात्रा बढ़ाएँ।`,
    reviewAgain: "दूसरा अनुरोध शुरू करने से पहले ऑर्डर की पुष्टि या रद्द करें।",
    approvalNeeded: "जोड़ने से पहले उपलब्ध मात्रा स्वीकार करने का विकल्प चुनें।",
    cancelled: "ठीक है, वॉइस ऑर्डर रद्द कर दिया।",
    itemRemoved: "इस वॉइस ऑर्डर से आइटम हटा दिया।",
    itemRemovedLast: "इस वॉइस ऑर्डर से आइटम हटा दिया।",
    cartAdded: "आपके आइटम कार्ट में जोड़ दिए गए हैं। क्या चेकआउट पर जाएँ?",
    cartError: "कार्ट अपडेट नहीं हो सका। फिर कोशिश करें या आइटम मैन्युअल रूप से जोड़ें।",
    continueBrowsing: "ठीक है। आप उत्पाद देखना जारी रख सकते हैं।",
    proceedPrompt: "‘चेकआउट पर जाएँ’ कहें या ‘खरीदारी जारी रखें’ चुनें।",
    unavailableError: "उत्पाद सूची लोड नहीं हो सकी। फिर से कनेक्ट करें या पेज रीफ़्रेश करें।",
    didntCatch: "सुनाई नहीं दिया। कृपया फिर से बोलें।",
    noSpeech: "सुनाई नहीं दिया। कृपया फिर से बोलें।",
    listening: "सुन रहा हूँ…",
    userSaid: "आपने कहा",
    order: "आपका ऑर्डर",
    onlyAvailable: (quantity, name) => `${name} के केवल ${quantity} किलो उपलब्ध हैं। क्या उपलब्ध मात्रा जोड़ें?`,
    addAvailable: (quantity) => `${quantity} किलो जोड़ें`,
    cancelItem: "आइटम रद्द करें",
    availableAccepted: "उपलब्ध मात्रा स्वीकार की गई।",
    estimatedTotal: "अनुमानित कुल",
    confirmAdd: "पुष्टि करें और कार्ट में जोड़ें",
    adding: "जोड़ा जा रहा है…",
    checkout: "चेकआउट पर जाएँ",
    continueShopping: "खरीदारी जारी रखें",
    startVoice: "वॉइस ऑर्डर शुरू करें",
    starting: "शुरू हो रहा है…",
  },
  "kn-IN": {
    greeting: (name) => `ನಮಸ್ಕಾರ${name ? ` ${name}` : ""}! ಏನು ಆರ್ಡರ್ ಮಾಡಲು ಬಯಸುತ್ತೀರಿ?`,
    loadingError: "ಉತ್ಪನ್ನಗಳ ಪಟ್ಟಿಯನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಮರುಸಂಪರ್ಕಿಸಿ ಅಥವಾ ಪುಟವನ್ನು ರಿಫ್ರೆಶ್ ಮಾಡಿ.",
    notRecognized: "ಉತ್ಪನ್ನ ಮತ್ತು ಪ್ರಮಾಣ ಗುರುತಿಸಲಾಗಲಿಲ್ಲ. ಉದಾಹರಣೆಗೆ ಟೊಮೆಟೊ ಒಂದು ಕಿಲೋ ಎಂದು ಹೇಳಿ.",
    unsupported: "ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಧ್ವನಿ ಗುರುತಿಸುವಿಕೆ ಲಭ್ಯವಿಲ್ಲ. Chrome ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಉತ್ಪನ್ನಗಳನ್ನು ಕೈಯಾರೆ ಸೇರಿಸಿ.",
    micDenied: "ಮೈಕ್ರೊಫೋನ್ ಅನುಮತಿ ನಿರಾಕರಿಸಲಾಗಿದೆ. ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಅನುಮತಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    speechFailed: "ಧ್ವನಿ ಗುರುತಿಸುವಿಕೆ ವಿಫಲವಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಕೈಯಾರೆ ಸೇರಿಸಿ.",
    micFailed: "ಮೈಕ್ರೊಫೋನ್ ಪ್ರಾರಂಭಿಸಲಾಗಲಿಲ್ಲ. ಅನುಮತಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    notAvailable: (names) => `${names} ನಮ್ಮ ಉತ್ಪನ್ನ ಪಟ್ಟಿಯಲ್ಲಿ ಲಭ್ಯವಿಲ್ಲ; ಸೇರಿಸಲಾಗುವುದಿಲ್ಲ.`,
    outOfStock: (names) => `${names} ಪ್ರಸ್ತುತ ಸ್ಟಾಕ್‌ನಲ್ಲಿ ಇಲ್ಲ.`,
    alreadyCart: (names) => `${names} ಲಭ್ಯವಿರುವ ಸ್ಟಾಕ್ ಈಗಾಗಲೇ ನಿಮ್ಮ ಕಾರ್ಟ್‌ನಲ್ಲಿದೆ.`,
    stockUnknown: (names) => `${names} ಸ್ಟಾಕ್ ಅಥವಾ ಬೆಲೆಯನ್ನು ಪರಿಶೀಲಿಸಲಾಗಲಿಲ್ಲ. ಸೇರಿಸಲಾಗುವುದಿಲ್ಲ.`,
    review: (items, total) => `ನಿಮ್ಮ ಆರ್ಡರ್ ಒಟ್ಟು ₹${total}. ${items} ಕಂಡುಬಂದಿವೆ. ಇವುಗಳನ್ನು ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಬೇಕೆ?`,
    minimumOrder: (total, minimum) => `ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಆರ್ಡರ್ ಒಟ್ಟು ₹${total}. ಕನಿಷ್ಠ ಆರ್ಡರ್ ಮೌಲ್ಯ ₹${minimum}. ದಯವಿಟ್ಟು ಇನ್ನೊಂದು ಉತ್ಪನ್ನ ಸೇರಿಸಿ ಅಥವಾ ಪ್ರಮಾಣ ಹೆಚ್ಚಿಸಿ.`,
    reviewAgain: "ಹೊಸ ವಿನಂತಿಗೂ ಮೊದಲು ಆರ್ಡರ್ ದೃಢೀಕರಿಸಿ ಅಥವಾ ರದ್ದುಗೊಳಿಸಿ.",
    approvalNeeded: "ಸೇರಿಸುವ ಮೊದಲು ಲಭ್ಯವಿರುವ ಪ್ರಮಾಣವನ್ನು ಒಪ್ಪಿಕೊಳ್ಳಿ.",
    cancelled: "ಸರಿ, ಧ್ವನಿ ಆರ್ಡರ್ ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ.",
    itemRemoved: "ಈ ಧ್ವನಿ ಆರ್ಡರ್‌ನಿಂದ ಐಟಂ ತೆಗೆದುಹಾಕಲಾಗಿದೆ.",
    itemRemovedLast: "ಈ ಧ್ವನಿ ಆರ್ಡರ್‌ನಿಂದ ಐಟಂ ತೆಗೆದುಹಾಕಲಾಗಿದೆ.",
    cartAdded: "ಐಟಂಗಳನ್ನು ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಲಾಗಿದೆ. ಚೆಕ್‌ಔಟ್‌ಗೆ ಮುಂದುವರಿಯಬೇಕೆ?",
    cartError: "ಕಾರ್ಟ್ ನವೀಕರಿಸಲಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಕೈಯಾರೆ ಸೇರಿಸಿ.",
    continueBrowsing: "ಸರಿ. ಉತ್ಪನ್ನಗಳನ್ನು ವೀಕ್ಷಿಸುವುದನ್ನು ಮುಂದುವರಿಸಿ.",
    proceedPrompt: "ಚೆಕ್‌ಔಟ್‌ಗೆ ಹೋಗಿ ಎಂದು ಹೇಳಿ ಅಥವಾ ಶಾಪಿಂಗ್ ಮುಂದುವರಿಸಿ ಆಯ್ಕೆಮಾಡಿ.",
    unavailableError: "ಉತ್ಪನ್ನಗಳ ಪಟ್ಟಿಯನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಮರುಸಂಪರ್ಕಿಸಿ ಅಥವಾ ಪುಟವನ್ನು ರಿಫ್ರೆಶ್ ಮಾಡಿ.",
    didntCatch: "ಸರಿಯಾಗಿ ಕೇಳಿಸಲಿಲ್ಲ. ಮತ್ತೆ ಮಾತನಾಡಿ.",
    noSpeech: "ಸರಿಯಾಗಿ ಕೇಳಿಸಲಿಲ್ಲ. ಮತ್ತೆ ಮಾತನಾಡಿ.",
    listening: "ಕೇಳುತ್ತಿದ್ದೇನೆ…",
    userSaid: "ನೀವು ಹೇಳಿದ್ದು",
    order: "ನಿಮ್ಮ ಆರ್ಡರ್",
    onlyAvailable: (quantity, name) => `${name} ${quantity} ಕೆಜಿ ಮಾತ್ರ ಲಭ್ಯವಿದೆ. ಲಭ್ಯವಿರುವುದನ್ನು ಸೇರಿಸಬೇಕೆ?`,
    addAvailable: (quantity) => `${quantity} ಕೆಜಿ ಸೇರಿಸಿ`,
    cancelItem: "ಐಟಂ ರದ್ದುಮಾಡಿ",
    availableAccepted: "ಲಭ್ಯವಿರುವ ಪ್ರಮಾಣವನ್ನು ಒಪ್ಪಲಾಗಿದೆ.",
    estimatedTotal: "ಅಂದಾಜು ಮೊತ್ತ",
    confirmAdd: "ದೃಢೀಕರಿಸಿ ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ",
    adding: "ಸೇರಿಸಲಾಗುತ್ತಿದೆ…",
    checkout: "ಚೆಕ್‌ಔಟ್‌ಗೆ ಮುಂದುವರಿಯಿರಿ",
    continueShopping: "ಶಾಪಿಂಗ್ ಮುಂದುವರಿಸಿ",
    startVoice: "ಧ್ವನಿ ಆರ್ಡರ್ ಪ್ರಾರಂಭಿಸಿ",
    starting: "ಪ್ರಾರಂಭಿಸಲಾಗುತ್ತಿದೆ…",
  },
  "ta-IN": {
    greeting: (name) => `வணக்கம்${name ? ` ${name}` : ""}! என்ன ஆர்டர் செய்ய விரும்புகிறீர்கள்?`,
    loadingError: "பொருள் பட்டியலை ஏற்ற முடியவில்லை. மீண்டும் இணைக்கவும் அல்லது பக்கத்தைப் புதுப்பிக்கவும்.",
    notRecognized: "பொருளையும் அளவையும் அடையாளம் காண முடியவில்லை. உதாரணம்: தக்காளி ஒரு கிலோ.",
    unsupported: "இந்த உலாவியில் குரல் அடையாளம் இல்லை. Chrome முயற்சிக்கவும் அல்லது பொருட்களை கைமுறையாகச் சேர்க்கவும்.",
    micDenied: "மைக்ரோஃபோன் அனுமதி மறுக்கப்பட்டது. உலாவியில் அனுமதித்து மீண்டும் முயற்சிக்கவும்.",
    speechFailed: "குரல் அடையாளம் தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும் அல்லது கைமுறையாகச் சேர்க்கவும்.",
    micFailed: "மைக்ரோஃபோனைத் தொடங்க முடியவில்லை. அனுமதியைச் சரிபார்த்து முயற்சிக்கவும்.",
    notAvailable: (names) => `${names} எங்கள் பொருள் பட்டியலில் இல்லை; சேர்க்கப்படாது.`,
    outOfStock: (names) => `${names} தற்போது கையிருப்பில் இல்லை.`,
    alreadyCart: (names) => `${names} கிடைக்கும் கையிருப்பு ஏற்கனவே உங்கள் கார்ட்டில் உள்ளது.`,
    stockUnknown: (names) => `${names} கையிருப்பு அல்லது விலையைச் சரிபார்க்க முடியவில்லை; சேர்க்கப்படாது.`,
    review: (items, total) => `உங்கள் ஆர்டர் மொத்தம் ₹${total}. ${items} கிடைத்தன. இவற்றை கார்ட்டில் சேர்க்கலாமா?`,
    minimumOrder: (total, minimum) => `உங்கள் தற்போதைய ஆர்டர் மொத்தம் ₹${total}. குறைந்தபட்ச ஆர்டர் மதிப்பு ₹${minimum}. மற்றொரு பொருளைச் சேர்க்கவும் அல்லது அளவை அதிகரிக்கவும்.`,
    reviewAgain: "அடுத்த கோரிக்கைக்கு முன் ஆர்டரை உறுதிப்படுத்தவும் அல்லது ரத்துசெய்யவும்.",
    approvalNeeded: "சேர்ப்பதற்கு முன் கிடைக்கும் அளவை ஏற்கவும்.",
    cancelled: "சரி, குரல் ஆர்டர் ரத்துசெய்யப்பட்டது.",
    itemRemoved: "இந்த குரல் ஆர்டரிலிருந்து பொருள் நீக்கப்பட்டது.",
    itemRemovedLast: "இந்த குரல் ஆர்டரிலிருந்து பொருள் நீக்கப்பட்டது.",
    cartAdded: "பொருட்கள் கார்ட்டில் சேர்க்கப்பட்டன. செக்அவுட்டுக்குச் செல்லலாமா?",
    cartError: "கார்ட்டைப் புதுப்பிக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும் அல்லது கைமுறையாகச் சேர்க்கவும்.",
    continueBrowsing: "சரி. பொருட்களைத் தொடர்ந்து பார்க்கலாம்.",
    proceedPrompt: "செக்அவுட்டுக்குச் செல்லுங்கள் என்று சொல்லவும் அல்லது ஷாப்பிங்கைத் தொடரவும்.",
    unavailableError: "பொருள் பட்டியலை ஏற்ற முடியவில்லை. மீண்டும் இணைக்கவும் அல்லது பக்கத்தைப் புதுப்பிக்கவும்.",
    didntCatch: "கேட்கவில்லை. மீண்டும் பேசவும்.",
    noSpeech: "கேட்கவில்லை. மீண்டும் பேசவும்.",
    listening: "கேட்கிறது…",
    userSaid: "நீங்கள் சொன்னது",
    order: "உங்கள் ஆர்டர்",
    onlyAvailable: (quantity, name) => `${name} ${quantity} கிலோ மட்டுமே உள்ளது. கிடைப்பதைச் சேர்க்கலாமா?`,
    addAvailable: (quantity) => `${quantity} கிலோ சேர்க்கவும்`,
    cancelItem: "பொருளை ரத்துசெய்",
    availableAccepted: "கிடைக்கும் அளவு ஏற்கப்பட்டது.",
    estimatedTotal: "மதிப்பிடப்பட்ட மொத்தம்",
    confirmAdd: "உறுதிசெய்து கார்ட்டில் சேர்",
    adding: "சேர்க்கிறது…",
    checkout: "செக்அவுட்டுக்குச் செல்லவும்",
    continueShopping: "ஷாப்பிங்கைத் தொடரவும்",
    startVoice: "குரல் ஆர்டரைத் தொடங்கு",
    starting: "தொடங்குகிறது…",
  },
  "ml-IN": {
    greeting: (name) => `നമസ്കാരം${name ? ` ${name}` : ""}! എന്താണ് ഓർഡർ ചെയ്യേണ്ടത്?`,
    loadingError: "ഉൽപ്പന്നങ്ങളുടെ പട്ടിക ലോഡ് ചെയ്യാനായില്ല. വീണ്ടും കണക്റ്റ് ചെയ്ത് പേജ് പുതുക്കുക.",
    notRecognized: "ഉൽപ്പന്നവും അളവും തിരിച്ചറിയാനായില്ല. ഉദാഹരണം: തക്കാളി ഒരു കിലോ.",
    unsupported: "ഈ ബ്രൗസറിൽ ശബ്ദ തിരിച്ചറിയൽ ലഭ്യമല്ല. Chrome ഉപയോഗിക്കുക അല്ലെങ്കിൽ ഉൽപ്പന്നങ്ങൾ കൈകൊണ്ട് ചേർക്കുക.",
    micDenied: "മൈക്രോഫോൺ അനുമതി നിരസിച്ചു. ബ്രൗസറിൽ അനുമതി നൽകി വീണ്ടും ശ്രമിക്കുക.",
    speechFailed: "ശബ്ദ തിരിച്ചറിയൽ പരാജയപ്പെട്ടു. വീണ്ടും ശ്രമിക്കുക അല്ലെങ്കിൽ കൈകൊണ്ട് ചേർക്കുക.",
    micFailed: "മൈക്രോഫോൺ ആരംഭിക്കാനായില്ല. അനുമതി പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.",
    notAvailable: (names) => `${names} ഉൽപ്പന്ന പട്ടികയിൽ ലഭ്യമല്ല; ചേർക്കില്ല.`,
    outOfStock: (names) => `${names} ഇപ്പോൾ സ്റ്റോക്കില്ല.`,
    alreadyCart: (names) => `${names} ലഭ്യമായ സ്റ്റോക്ക് ഇതിനകം കാർട്ടിലുണ്ട്.`,
    stockUnknown: (names) => `${names} സ്റ്റോക്കോ വിലയോ പരിശോധിക്കാനായില്ല; ചേർക്കില്ല.`,
    review: (items, total) => `നിങ്ങളുടെ ഓർഡർ ആകെ ₹${total}. ${items} കണ്ടെത്തി. ഇവ കാർട്ടിൽ ചേർക്കട്ടേ?`,
    minimumOrder: (total, minimum) => `നിങ്ങളുടെ നിലവിലെ ഓർഡർ ആകെ ₹${total}. കുറഞ്ഞ ഓർഡർ മൂല്യം ₹${minimum}. മറ്റൊരു ഉൽപ്പന്നം ചേർക്കുകയോ അളവ് കൂട്ടുകയോ ചെയ്യുക.`,
    reviewAgain: "മറ്റൊരു അഭ്യർത്ഥനയ്ക്ക് മുമ്പ് ഓർഡർ ഉറപ്പാക്കുകയോ റദ്ദാക്കുകയോ ചെയ്യുക.",
    approvalNeeded: "ചേർക്കുന്നതിന് മുമ്പ് ലഭ്യമായ അളവ് സ്വീകരിക്കുക.",
    cancelled: "ശരി, വോയ്സ് ഓർഡർ റദ്ദാക്കി.",
    itemRemoved: "ഈ വോയ്സ് ഓർഡറിൽ നിന്ന് ഇനം നീക്കി.",
    itemRemovedLast: "ഈ വോയ്സ് ഓർഡറിൽ നിന്ന് ഇനം നീക്കി.",
    cartAdded: "ഇനങ്ങൾ കാർട്ടിൽ ചേർത്തു. ചെക്ക്ഔട്ടിലേക്ക് പോകണോ?",
    cartError: "കാർട്ട് പുതുക്കാനായില്ല. വീണ്ടും ശ്രമിക്കുക അല്ലെങ്കിൽ കൈകൊണ്ട് ചേർക്കുക.",
    continueBrowsing: "ശരി. ഉൽപ്പന്നങ്ങൾ കാണുന്നത് തുടരാം.",
    proceedPrompt: "ചെക്ക്ഔട്ടിലേക്ക് പോകുക എന്ന് പറയുക അല്ലെങ്കിൽ ഷോപ്പിംഗ് തുടരുക തിരഞ്ഞെടുക്കുക.",
    unavailableError: "ഉൽപ്പന്നങ്ങളുടെ പട്ടിക ലോഡ് ചെയ്യാനായില്ല. വീണ്ടും കണക്റ്റ് ചെയ്ത് പേജ് പുതുക്കുക.",
    didntCatch: "വ്യക്തമായി കേട്ടില്ല. വീണ്ടും പറയുക.",
    noSpeech: "വ്യക്തമായി കേട്ടില്ല. വീണ്ടും പറയുക.",
    listening: "കേൾക്കുന്നു…",
    userSaid: "നിങ്ങൾ പറഞ്ഞത്",
    order: "നിങ്ങളുടെ ഓർഡർ",
    onlyAvailable: (quantity, name) => `${name} ${quantity} കിലോ മാത്രമേ ലഭ്യമുള്ളൂ. ലഭ്യമായത് ചേർക്കണോ?`,
    addAvailable: (quantity) => `${quantity} കിലോ ചേർക്കുക`,
    cancelItem: "ഇനം റദ്ദാക്കുക",
    availableAccepted: "ലഭ്യമായ അളവ് അംഗീകരിച്ചു.",
    estimatedTotal: "കണക്കാക്കിയ ആകെ തുക",
    confirmAdd: "ഉറപ്പാക്കി കാർട്ടിൽ ചേർക്കുക",
    adding: "ചേർക്കുന്നു…",
    checkout: "ചെക്ക്ഔട്ടിലേക്ക് പോകുക",
    continueShopping: "ഷോപ്പിംഗ് തുടരുക",
    startVoice: "വോയ്സ് ഓർഡർ തുടങ്ങുക",
    starting: "തുടങ്ങുന്നു…",
  },
  "mr-IN": {
    greeting: (name) => `नमस्कार${name ? ` ${name}` : ""}! तुम्हाला काय ऑर्डर करायचे आहे?`,
    loadingError: "उत्पादनांची यादी लोड झाली नाही. पुन्हा कनेक्ट करा किंवा पृष्ठ रिफ्रेश करा.",
    notRecognized: "उत्पादन आणि प्रमाण ओळखता आले नाही. उदाहरण: टोमॅटो एक किलो.",
    unsupported: "या ब्राउझरमध्ये व्हॉइस ओळख उपलब्ध नाही. Chrome वापरा किंवा उत्पादने स्वतः जोडा.",
    micDenied: "मायक्रोफोनची परवानगी नाकारली. ब्राउझरमध्ये परवानगी देऊन पुन्हा प्रयत्न करा.",
    speechFailed: "व्हॉइस ओळख अयशस्वी झाली. पुन्हा प्रयत्न करा किंवा उत्पादने स्वतः जोडा.",
    micFailed: "मायक्रोफोन सुरू करता आला नाही. परवानगी तपासून पुन्हा प्रयत्न करा.",
    notAvailable: (names) => `${names} उत्पादनांच्या यादीत नाहीत; जोडले जाणार नाहीत.`,
    outOfStock: (names) => `${names} सध्या स्टॉकमध्ये नाहीत.`,
    alreadyCart: (names) => `${names} चा उपलब्ध स्टॉक आधीच तुमच्या कार्टमध्ये आहे.`,
    stockUnknown: (names) => `${names} चा स्टॉक किंवा किंमत तपासता आली नाही; जोडले जाणार नाहीत.`,
    review: (items, total) => `तुमच्या ऑर्डरची एकूण रक्कम ₹${total}. ${items} सापडले. हे पदार्थ कार्टमध्ये जोडू का?`,
    minimumOrder: (total, minimum) => `तुमच्या सध्याच्या ऑर्डरची एकूण रक्कम ₹${total}. किमान ऑर्डर मूल्य ₹${minimum} आहे. कृपया आणखी पदार्थ जोडा किंवा प्रमाण वाढवा.`,
    reviewAgain: "नवीन विनंतीपूर्वी ऑर्डरची पुष्टी करा किंवा रद्द करा.",
    approvalNeeded: "जोडण्यापूर्वी उपलब्ध प्रमाण स्वीकारायचे ते निवडा.",
    cancelled: "ठीक आहे, व्हॉइस ऑर्डर रद्द केली.",
    itemRemoved: "या व्हॉइस ऑर्डरमधून वस्तू काढली.",
    itemRemovedLast: "या व्हॉइस ऑर्डरमधून वस्तू काढली.",
    cartAdded: "वस्तू कार्टमध्ये जोडल्या. चेकआउटकडे जायचे का?",
    cartError: "कार्ट अपडेट करता आली नाही. पुन्हा प्रयत्न करा किंवा वस्तू स्वतः जोडा.",
    continueBrowsing: "ठीक आहे. उत्पादने पाहणे सुरू ठेवा.",
    proceedPrompt: "चेकआउटकडे जा असे सांगा किंवा खरेदी सुरू ठेवा निवडा.",
    unavailableError: "उत्पादनांची यादी लोड झाली नाही. पुन्हा कनेक्ट करा किंवा पृष्ठ रिफ्रेश करा.",
    didntCatch: "ऐकू आले नाही. कृपया पुन्हा बोला.",
    noSpeech: "ऐकू आले नाही. कृपया पुन्हा बोला.",
    listening: "ऐकत आहे…",
    userSaid: "तुम्ही म्हणालात",
    order: "तुमची ऑर्डर",
    onlyAvailable: (quantity, name) => `${name} फक्त ${quantity} किलो उपलब्ध आहे. उपलब्ध प्रमाण जोडायचे?`,
    addAvailable: (quantity) => `${quantity} किलो जोडा`,
    cancelItem: "वस्तू रद्द करा",
    availableAccepted: "उपलब्ध प्रमाण मान्य केले.",
    estimatedTotal: "अंदाजित एकूण",
    confirmAdd: "पुष्टी करून कार्टमध्ये जोडा",
    adding: "जोडत आहे…",
    checkout: "चेकआउटकडे जा",
    continueShopping: "खरेदी सुरू ठेवा",
    startVoice: "व्हॉइस ऑर्डर सुरू करा",
    starting: "सुरू करत आहे…",
  },
  "bn-IN": {
    greeting: (name) => `নমস্কার${name ? ` ${name}` : ""}! আপনি কী অর্ডার করতে চান?`,
    loadingError: "পণ্যের তালিকা লোড করা যায়নি। আবার সংযোগ করুন বা পৃষ্ঠা রিফ্রেশ করুন।",
    notRecognized: "পণ্য ও পরিমাণ বুঝতে পারিনি। উদাহরণ: টমেটো এক কেজি।",
    unsupported: "এই ব্রাউজারে ভয়েস শনাক্তকরণ নেই। Chrome ব্যবহার করুন বা পণ্য হাতে যোগ করুন।",
    micDenied: "মাইক্রোফোনের অনুমতি নেই। ব্রাউজারে অনুমতি দিয়ে আবার চেষ্টা করুন।",
    speechFailed: "ভয়েস শনাক্তকরণ ব্যর্থ হয়েছে। আবার চেষ্টা করুন বা পণ্য হাতে যোগ করুন।",
    micFailed: "মাইক্রোফোন চালু করা যায়নি। অনুমতি পরীক্ষা করে আবার চেষ্টা করুন।",
    notAvailable: (names) => `${names} পণ্যের তালিকায় নেই; যোগ করা হবে না।`,
    outOfStock: (names) => `${names} বর্তমানে স্টকে নেই।`,
    alreadyCart: (names) => `${names}-এর উপলভ্য স্টক ইতিমধ্যে আপনার কার্টে আছে।`,
    stockUnknown: (names) => `${names}-এর স্টক বা দাম যাচাই করা যায়নি; যোগ হবে না।`,
    review: (items, total) => `আপনার অর্ডারের মোট ₹${total}। ${items} পাওয়া গেছে। এগুলি কার্টে যোগ করব?`,
    minimumOrder: (total, minimum) => `আপনার বর্তমান অর্ডারের মোট ₹${total}। ন্যূনতম অর্ডার মূল্য ₹${minimum}। অনুগ্রহ করে আরেকটি পণ্য যোগ করুন বা পরিমাণ বাড়ান।`,
    reviewAgain: "নতুন অনুরোধের আগে অর্ডার নিশ্চিত করুন বা বাতিল করুন।",
    approvalNeeded: "যোগ করার আগে উপলভ্য পরিমাণ গ্রহণ করবেন কি না বেছে নিন।",
    cancelled: "ঠিক আছে, ভয়েস অর্ডার বাতিল করেছি।",
    itemRemoved: "এই ভয়েস অর্ডার থেকে পণ্যটি সরানো হয়েছে।",
    itemRemovedLast: "এই ভয়েস অর্ডার থেকে পণ্যটি সরানো হয়েছে।",
    cartAdded: "পণ্যগুলি কার্টে যোগ হয়েছে। চেকআউটে যাবেন?",
    cartError: "কার্ট আপডেট করা যায়নি। আবার চেষ্টা করুন বা পণ্য হাতে যোগ করুন।",
    continueBrowsing: "ঠিক আছে। পণ্য দেখা চালিয়ে যান।",
    proceedPrompt: "চেকআউটে যান বলুন অথবা কেনাকাটা চালিয়ে যান বেছে নিন।",
    unavailableError: "পণ্যের তালিকা লোড করা যায়নি। আবার সংযোগ করুন বা পৃষ্ঠা রিফ্রেশ করুন।",
    didntCatch: "শুনতে পাইনি। আবার বলুন।",
    noSpeech: "শুনতে পাইনি। আবার বলুন।",
    listening: "শুনছি…",
    userSaid: "আপনি বলেছেন",
    order: "আপনার অর্ডার",
    onlyAvailable: (quantity, name) => `${name} মাত্র ${quantity} কেজি আছে। উপলভ্য পরিমাণ যোগ করব?`,
    addAvailable: (quantity) => `${quantity} কেজি যোগ করুন`,
    cancelItem: "পণ্য বাতিল করুন",
    availableAccepted: "উপলভ্য পরিমাণ গ্রহণ করা হয়েছে।",
    estimatedTotal: "আনুমানিক মোট",
    confirmAdd: "নিশ্চিত করে কার্টে যোগ করুন",
    adding: "যোগ হচ্ছে…",
    checkout: "চেকআউটে যান",
    continueShopping: "কেনাকাটা চালিয়ে যান",
    startVoice: "ভয়েস অর্ডার শুরু করুন",
    starting: "শুরু হচ্ছে…",
  },
};

export const getVoiceCopy = (languageCode) => COPY[languageCode] || COPY["en-IN"];
